name: Update BCV Rate & PWA Version

on:
  schedule:
    # Runs every 6 hours (4 times daily) - 00:00, 06:00, 12:00, 18:00 UTC
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-rate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
        
    - name: Run update script
      run: python scripts/update_rate.py

    - name: Update service worker version
      run: |
        # Update SW_VERSION in sw.js to trigger PWA cache update
        timestamp=$(date +%s)
        sed -i "s/const SW_VERSION = .*/const SW_VERSION = $timestamp;/" sw.js
        echo "Updated SW_VERSION to $timestamp"

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add -A
        timestamp=$(date -u)
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: ${timestamp}" && git push)